apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws-deployment
  labels:
    app: staticws  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staticws
  template:
    metadata:
      labels:
        app: staticws
    spec:
      containers:
      - name: staticws
        image: sim007/staticws:latest
        ports:
        -  containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: staticws-service
spec:
  selector:
    app: staticws
  ports:
  - protocol: TCP
    port: 4225
    targetPort: 80
  type: LoadBalancer 